### ISSUE TITLE
TravisCI build error: The command "bikeshed update" failed and exited with 1 during .

### ISSUE THREAD

**Issue by mfalken** [w3c/clipboard-apis#144]
https://github.com/w3c/clipboard-apis/pull/143 has a build error which looks like an infra problem:
https://travis-ci.com/github/w3c/clipboard-apis/builds/226470464

$ bikeshed update
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typing-extensions 3.10.0.0 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('typing-extensions<3.8,>=3.7.4.1'), {'widlparser'})

The command "bikeshed update" failed and exited with 1 during .

**Comment by annevk** [comment]
Maybe @marcoscaceres can help moving this away from Travis and unto W3C's publishing utility?
